### ISSUE TITLE
[Location Request] Mumbai, India

### ISSUE THREAD

**Issue by skyrideraj** [Nickersoft/cityhop.cafe#16]
### Do you prefer a walking or driving video (or both)?

- [x] Walking
- [ ] Driving

### Do you have any preference on the setting?

**Weather**

- [x] Rainy
- [ ] Snowy

**Time of Day**

- [x] Morning
- [ ] Mid-day
- [x] Evening
- [x] Night

**Comment by Nickersoft** [comment]
Hey @skyrideraj! Thanks for requesting a location – I actually original _had_ Mumbai as a walking video, but took it down because the guy filming kept narrating. Unfortunately, he uploads the longest videos of India, so his videos are best suited for the site. I rewatched his Mumbai video though and realized he doesn't narrate as much as I thought he does. Plus, you could always just turn down the volume. 

Sadly it's not rainy, but the video does feature a mix of day + night scenes. [Added!](https://www.cityhop.cafe/?v=OFc0WlRYMXowMkU6Y19fQnIxeFVWSzg=)
